<?php
/**
 * @var PHPEngine $view
 */

use Valkyrja\View\PHPEngine;

$view->setLayout('layout');
?>

<?php $view->startBlock('title'); ?>
    <img src="https://i.imgur.com/bnZA2RT.png" width="400">
<?php $view->endBlock('title'); ?>

<?php $view->startBlock('content'); ?>
    <div class="links">
        <a href="http://www.valkyrja.io/documentation">Documentation</a>
        &middot;
        <a href="https://github.com/valkyrjaio/valkyrja">GitHub</a>
        &middot;
        <a href="https://github.com/valkyrjaio/valkyrja/issues">Issues</a>
    </div>
<?php $view->endBlock('content'); ?>
