@layout('layout')

@startblock('title')
    <img src="https://i.imgur.com/bnZA2RT.png" width="400" alt="Valkyrja">
@endblock

@startblock('content')
    <div class="links">
        <a href="http://www.valkyrja.io/documentation">Documentation</a>
        &middot;
        <a href="https://github.com/valkyrjaio/valkyrja">GitHub</a>
        &middot;
        <a href="https://github.com/valkyrjaio/valkyrja/issues">Issues</a>
    </div>
@endblock
