<?php
/**
 * @var Template $template
 */

use Valkyrja\View\Template;

?>

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Valkyrja</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Oswald|Tangerine"
              rel="stylesheet" type="text/css">

        <!-- Styles -->
        <style>
            html, body
            {
                background-color : #fff;
                color            : #636b6f;
                font-family      : 'Oswald', sans-serif;
                font-weight      : normal;
                letter-spacing   : 1px;
                height           : 100vh;
                margin           : 0;
            }

            *
            {
                z-index : 1;
            }

            *::selection
            {
                background : rgba(130, 94, 163, .2);
            }

            .full-height
            {
                height : 100vh;
            }

            .flex-center
            {
                align-items     : center;
                display         : flex;
                justify-content : center;
            }

            .position-ref
            {
                position : relative;
            }

            .content
            {
                text-align : center;
            }

            .title
            {
                font-size   : 100px;
                font-family : 'Tangerine', sans-serif;
                font-weight : 300;
                padding     : 0;
                margin      : 0 auto;
            }

            .links a
            {
                color           : #636b6f;
                padding         : 0 25px;
                font-size       : 12px;
                font-weight     : 600;
                letter-spacing  : .1rem;
                text-decoration : none;
                text-transform  : uppercase;
            }

            .links a:hover
            {
                text-decoration : underline;
            }
        </style>
    </head>
    <body>
        <div class="flex-center position-ref full-height">
            <div class="content">
                <div class="title">
                    <?php echo $template->getBlock('title'); ?>
                </div>

                <?php echo $template->getBlock('content'); ?>
            </div>
        </div>
    </body>
</html>
