#!/usr/bin/env php
<?php

declare(strict_types=1);

use App\Entry\App;
use Env\EnvCli;

require_once __DIR__ . '/vendor/autoload.php';

try {
    App::cli(EnvCli::APP_DIR, new EnvCli());
} catch (Throwable $throwable) {
    var_dump($throwable);
}
