<?php
/**
 * @var TemplateContract $template
 * @var string           $value
 */

use Valkyrja\View\Template\Contract\TemplateContract;

$template->setLayout('layout');
?>

<?php $template->startBlock('title'); ?>
Dynamic
<?php $template->endBlock('title'); ?>

<?php $template->startBlock('content'); ?>
<article>
    Test Php Dynamic Url with value: <?php echo $value; ?>
</article>
<?php $template->endBlock('content'); ?>
